### PR TITLE
[tracer] Enable dynamic tracing even if global trace_on is disabled

### LINKED ISSUE #2240: [BUG] Dynamic sip tracing not enabled on creation
**OpenSIPS version you are running**
```
version: opensips 3.1.0 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
git revision: unknown
main.c compiled on 11:12:50 Sep  4 2020 with gcc 8
```

**Describe the bug**
Hi team,

If I have in the script:
```
#### HEP module
loadmodule "proto_hep.so"
modparam("proto_hep", "hep_id", "[hep_dst] <ip>:<port>; transport=udp; version=3")
#### SIP Tracing module
loadmodule "tracer.so"
modparam("tracer", "trace_on", 0)
modparam("tracer", "trace_id", "[test]uri=hep:hep_dst")
```
and in several places of routing script:
`trace("test", "t");`

Tracing is disabled by default and it's very seldom when I want to enable it to get all the SIP traffic to HEP server or to DB. But of course, I can enable it with 'opensips-cli -x mi trace mode=on'
And I have opensips-cli and it's relatively often, when I want to trace some IP-address or user using console without enabling global tracing. I can create dynamic tracing, but OpenSIPS does not send anything to dynamically created destinations, as global tracing is disabled.
So how to use these short-living dynamic tracings without enabling all the statically configured destinations?

**To Reproduce**
1. Use module `tracer`, but set `trace_on=0`. Several static tracing destinations (to HEP, DB), which are used very seldom.
2. Start `opensips-cli` and use command `trace` to create dynamic tracing ID.
3. Nothing comes from OpenSIPS

**Expected behavior**
Dynamic tracing ID should be enabled by default without globally enabling all possible destinations.

**OS/environment information**
 - Operating System: CentOS Linux release 8.2.2004 (Core)
 - OpenSIPS installation: `git`
 - other relevant information:

### PR DESCRIPTION
**Pull request by vasilevalex**
Fixes #2240

### CODE REVIEW

**Comment by vasilevalex** [comment]
Please review, may be it's not the way it intended to work.

**Comment by vasilevalex** [comment]
waiting for review

**Comment by razvancrainea** [comment]
More or less, this is exactly how it is intended to work - if the tracing is disabled, dynamic tracing is also disabled.
As I said in ticket #2240 , I suspect that this commit enables tracing for all destinations, even the non-dynamic ones. Did you get a chance to check this?

**Comment by vasilevalex** [comment]
@razvancrainea I've rechecked the changes. When going through trace_list (static entries) it always checks (it->traceable && !(*it->traceable)) and during init stage this flag is set to the value of global `trace_on`. And I also made tests and I have traces in opensips-cli, but have nothing send over hep. So with this PR only dynamic tracing is enabled. static entries are still disabled.
But without this PR there is no way at all to enable dynamic tracing except global setting. For static entries it is possible to enable specific entry with `opensips-cli -x mi trace id=[some_trace_id] mode=on` but this `id` can belong to static list, dynamic completely omitted.

**Comment by vasilevalex** [comment]
up

**Comment by razvancrainea** [comment]
I've finally got some chance to run a few tests, and confirmed that the patch was not complete. As I previously said, `dyn_trace_list` always has a value, otherwise the module wouldn't load - therefore the check you did was useless, basically it was always false.
The problem appears in the following scenario:

1. start opensips with tracing off
2. enable tracing
3. enable specific tracing id
4. turn of tracing
5. start dynamic tracing (using cli)

At this point, both dynamic and static/script tracing is done, even though the global tracing is off, only specific id is on. This is not correct.
Therefore I will close this PR, I will soon push a fix on master. Will update #2240 when this is completed.
Kindly ask you to open a new PR for fixing the documentation though.

**Pull request closed without merging**
