### PR TITLE
Fix setting LIBDIR

### LINKED ISSUE #624: modules are incorrectly installed to lib instead of lib64 now
On master
commit: 079de59850d9b9e199c5ff5285ba11600a8d2faf

doing: make all && make all install

on a machine with:

# uname -a
Linux uphreak.com 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Installs all the modules to /usr/local/lib/opensips/modules instead of /usr/local/lib64/opensips/modules

This breaks configs that have previously specified mpath at lib64

### PR DESCRIPTION
**Pull request by saghul**
Should fix #624 

(untested)

### CODE REVIEW

**Comment by saghul** [comment]
@etamme tested it and it works!

Gotta go now, so can you merge it @razvancrainea or @bogdan-iancu? Otherwise I will when I get back. Thanks.

**Comment by bogdan-iancu** [comment]
Thank you @saghul

**Comment by saghul** [comment]
Guys, can you also merge this into the 1.11 branch? Thanks!

**Comment by razvancrainea** [comment]
Merged into 1.11 too.

**Pull request merged**
