### PR TITLE
osp: fix use of uninitialized pointer

### PR DESCRIPTION
**Pull request by l2dy**
See https://github.com/OpenSIPS/opensips/blob/47d9ec972118d3fa9ff0a0e134fb0b013f623a87/modules/osp/orig_transaction.c#L840-L842

### CODE REVIEW

**Comment by l2dy** [comment]
Maybe `OSPT_CALL_ID* callids[callidnumber] = {NULL};` is better?

**Comment by liviuchircu** [comment]
This code is completely bogus.  See line +737, it will crash anyway if we set the pointer to `NULL` and not exit on error.  We can merge this, but it really fixes nothing.

**Comment by liviuchircu** [comment]
No, I was wrong, there's a big `else` branch and my assessment was wrong.  Merging.

**Comment by l2dy** [comment]
> This code is completely bogus. See line +737, it will crash anyway if we set the pointer to `NULL` and not exit on error. We can merge this, but it really fixes nothing.

Line 737 is in the `else {}` block, so it would not be executed if ospGetCallId() failed, correct?

**Pull request merged**
