### PR TITLE
[cachedb_redis] cleanup stale context pointer, branch 3.1

### PR DESCRIPTION
**Pull request by john08burke**
Same as #2804 but for 3.1 branch.

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
@john08burke , could you check the correctness of my porting from 3.1 to 3.2, please https://github.com/OpenSIPS/opensips/commit/7cb182de0bf1f31dfe6e697b4321d0b7528268f3 ? there were some conflicts I had to resolve, so I need a bit of a double-checking :)

**Comment by bogdan-iancu** [comment]
Also see the additional 34e144783fab7c13bc238cfca9688981c6bf2af4 .

**Comment by john08burke** [comment]
@bogdan-iancu, it doesn't look quite right:
```
git fetch upstream
git checkout -b del_3.2 upstream/3.2
git reset --hard 2d49e1f3a89b751942c1b6340355edb38ef6446c
git cherry-pick d79f3765b35bd6268ca369b2152c379090bc5b2b
git diff del_3.2 upstream/3.2
```

The diff shows a few lines reordered (not a bit deal), but is missing 1 NULL assignment in `redis_connect_node`:
```
diff --git a/modules/cachedb_redis/cachedb_redis_dbase.c b/modules/cachedb_redis/cachedb_redis_dbase.c
index 55810a2fd..069d58ce5 100644
--- a/modules/cachedb_redis/cachedb_redis_dbase.c
+++ b/modules/cachedb_redis/cachedb_redis_dbase.c
@@ -151,7 +151,6 @@ int redis_connect_node(redis_con *con,cluster_node *node)
                redis_init_ssl(con->id->extra_options, node->context,
                        &node->tls_dom) < 0) {
                redisFree(node->context);
-               node->context = NULL;
                return -1;
        }
 #endif
@@ -185,11 +184,11 @@ int redis_connect_node(redis_con *con,cluster_node *node)
 
 error:
        redisFree(node->context);
-       node->context = NULL;
        if (use_tls && node->tls_dom) {
                tls_api.release_domain(node->tls_dom);
                node->tls_dom = NULL;
        }
+       node->context = NULL;
        return -1;
 }
 
diff --git a/modules/cachedb_redis/cachedb_redis_utils.c b/modules/cachedb_redis/cachedb_redis_utils.c
index 0579044bb..8bac7a7b5 100644
--- a/modules/cachedb_redis/cachedb_redis_utils.c
+++ b/modules/cachedb_redis/cachedb_redis_utils.c
@@ -109,10 +109,10 @@ void destroy_cluster_nodes(redis_con *con)
        new = con->nodes;
        while (new) {
                foo = new->next;
-               redisFree(new->context);
-               new->context = NULL;
                if (use_tls && new->tls_dom)
                        tls_api.release_domain(new->tls_dom);
+               redisFree(new->context);
+               new->context = NULL;
                pkg_free(new);
                new = foo;
        }
```

The 3.1 and master branch look good.  I'm not sure what your policies are, but could you rebase out the bad merge/fix on 3.2, then `git cherry-pick d79f3765b35bd6268ca369b2152c379090bc5b2b` (the master commit) and force push to 3.2?

**Comment by bogdan-iancu** [comment]
Thanks @john08burke , I hope 53017e0 re-aligns 3.2 code with the rest.

**Comment by john08burke** [comment]
@bogdan-iancu, LGTM!

**Pull request merged**
