### PR TITLE
Fix for Makefile.defs

### PR DESCRIPTION
**Pull request by bambyster**
I was working on a new FreeBSD port for opensips and found a bug in the Makefile.defs which prevented LDFLAGS from including additional library search directory. The current order of the ifeq/else/endif is:

ifeq (,$(CFLAGS)) : line 826
ifeq ($(mode), release) : line 832
endif   # CFLAGS not set : line 1330
else    #mode,release : line 1362
endif #mode=release : line 1389

so I've changed the order of ifeqs and my build succeeded.

Another important feature which is needed by FreeBSD port is ability to override variables INSTALL_BIN, INSTALL_MODULES, etc so it is possible to be able to strip binaries of debug symbols if needed.

### CODE REVIEW

**Comment by razvancrainea** [comment]
Not sure I understand the underlying problem, but your PR changes the logic of the `release` mode. Can you explain exactly what was the problem if the `if`s are not reversed?

**Comment by bambyster** [comment]
My problem was with the MOD_LDFLAGS not being set properly when I pass CFLAGS as an environment variable. So if CFLAGS is set then the section which initializes the MOD_LDFLAGS is never reached:
```
ifeq (,$(CFLAGS))
    ifeq ($(mode), release)
    endif # CFLAGS not set
    ...
    MOD_LDFLAGS=-shared $(LDFLAGS) : lines 1335-1377
    ...
else #mode,release
endif #mode=release
```
As you see the comments on elses and endifs contradict the actual logic in the Makefile.defs.

**Comment by razvancrainea** [comment]
I somehow think the problem is somewhere else - an unhandled architecture or compiler.
What's the compiler you are using?

**Comment by bambyster** [comment]
I'm using clang.

But still my main point here is that the real logic in the Makefile.defs differs from the logic stated in comments in the Makefile.defs. Which is why I tried to modify it to match the comments.

**Comment by razvancrainea** [comment]
You are actually right, the comments are indeed reversed, and I think your PR is valid.
I was initially thinking you hit another bug I've noticed - in `mode=debug`, there's no handling for `clang`, but most likely this is a different bug.
Thanks for the PR, will merge it now.

**Comment by razvancrainea** [comment]
sorry, accidentally closed it.

**Pull request merged**
