### PR TITLE
Fix b2bl clean segfault

### PR DESCRIPTION
**Pull request by ar45**
**Summary**

When `b2bl_clean` is run by timer current_processing_context is not set

**Details**

**Solution**

Allocate and set a context.
I'm not sure if this is the right way to do it, but at least in my case it avoids the crash.

**Compatibility**

**Closing issues**

### CODE REVIEW

**Comment by ar45** [comment]
Yes. @razvancrainea can you please review this?

**Comment by ar45** [comment]
b2b_clean_bt

**Comment by ar45** [comment]
@razvancrainea @bogdan-iancu can you have a look at this?

**Comment by razvancrainea** [comment]
Hi, @ar45 !

I don't think that this is the right approach, as you are creating a single context for both possible messages that are being sent. I think the right approach would be for the context to be created at the TM level - I believe that for request is, but looks like it is not for the a reply.
However, there is one thing that makes me curious - what is the scenario that leads to this crash? I am curious how a b2b clean triggers a dialog callback.

Best regards,
Răzvan

**Comment by ar45** [comment]
Still open

**Comment by bogdan-iancu** [comment]
@ar45 , to be able to progress here, could you check @razvancrainea 's question here ?

> However, there is one thing that makes me curious - what is the scenario that leads to this crash? I am curious how a b2b clean triggers a dialog callback.

**Pull request closed without merging**
