### PR TITLE
Fix for TCP socket selection

### PR DESCRIPTION
**Pull request by attermann**
Issue #2083:

Fix for TCP socket selection in tcp_conn_get() when client connections to opensips share the same ephemeral port on the client side.  This can happen when opensips is listening on more than one port, and a given client host/ip connects to that opensips on more than one of its listening ports.  Under these circumstances the client TCP stack will allow client connections to share a local port as long as the destination ip:port are different.

In opensips, when searching for a TCP socket to send over, the general search algorithm in tcp_conn_get only considers the destination ip:port and not the source ip:port.  What can happen as a result is, for example, if the same client host/ip registers two UAs on different opensips listening ports, when it comes time to send a call to one of the UAs, opensips will randomly send to the UA using the first TCP connection that it finds based on the destination ip:port search which will be the wrong connection half the time.

This patch causes "send_sock" to be passed to tcp_conn_get() from all of the modules that call it which contains the desired local ip:port to use.  This is used in the search algorithm in tcp_conn_get to prefer connections that match both source and destination ip:port first, and falls back to just destination ip:port matching as before if a more specific match can not be made.
Note that this search algorithm was implemented using an additional pass for the primary source and destination ip:port match.  This could be optimized by a more sophisticated check for both cases in a single pass but that would involve much care with locks and reference counters by a person more familiar with their implementation.

Below is an excerpt of extra debug logs after this patch showing correct socket selection in a scenario like that described above.  Prior to patch the first socket on the wrong port would have been selected, but after the patch that socket is skipped and the second (correct c=0x7f98e14342a0) socket is selected instead.

```
DBG:core:tcp_conn_get: 0  port 5555
DBG:core:print_ip: tcpconn_find: ip 2.2.2.2
DBG:core:tcp_conn_get: p1 a=0x7f98e1433d90, c=0x7f98e1433cc0, c->id=1848113304, alias port= 5555 src_port=5555 dst_port=5060
DBG:core:print_ip: src_ip=2.2.2.2
DBG:core:print_ip: dst_ip=1.1.1.1
DBG:core:tcp_conn_get: p1 a=0x7f98e1434370, c=0x7f98e14342a0, c->id=1848113305, alias port= 5555 src_port=5555 dst_port=7080
DBG:core:print_ip: src_ip=2.2.2.2
DBG:core:print_ip: dst_ip=1.1.1.1
DBG:core:tcp_conn_get: con found in state 0
DBG:core:tcp_conn_get: tcp connection found (0x7f98e14342a0), acquiring fd
```

### CODE REVIEW

**Comment by attermann** [comment]
Also note, I chose not to pass socket_info to tcp_conn_get() in modules/tls_mgm/tls_select.c:get_cur_connection() because I was was unsure about potential unintended side-effects.

```tcp_conn_get(msg->rcv.proto_reserved1, 0, 0, PROTO_NONE, &c, NULL/*fd*/, NULL/*send_sock*/);```

TODO: Evaluate if msg force_send_socket or another socket_info should be passed from here.

**Comment by attermann** [comment]
Anybody acting on pull requests still for this project?  While my use case of different ports talking to the same remote service might not be a common one, it still exposes and corrects something pretty fundamental in TCP socket selection. Hoping that somebody can review this soon and get it merged into 2.4 and later so that we don't have to keep merging it into future releases ourselves.

**Comment by bogdan-iancu** [comment]
@attermann , this topic is a bit delicate, grant me a bit of time to review it.

**Comment by attermann** [comment]
@bogdan-iancu No worries I completely understand. I just wanted to be sure that it wasn't overlooked.

BTW, I added another commit that changes the search slightly. As you'll see in the description of the new commit, I removed the "fallback" search of destination-only because I found that it cna return the wrong connection after the correct connection has closed.

**Comment by attermann** [comment]
Hi @bogdan-iancu.  Just checking-in to see if this might be included in the upcoming 2.4.9 release. Thanks.

**Comment by bogdan-iancu** [comment]
This patch was obsoleted by #2513 , thank you @attermann !

**Pull request closed without merging**
