### PR TITLE
Drouting module probing socket parameter

### LINKED ISSUE #1484: Drouting module socket parameter for probing gateways
When OpenSIPS has serveral listening sockets, it is impossible to specify which one must be used to probe status of gateways. It will use the first one from configuration file.
But for example, in cluster configuration with Virtual IP moving between servers this causes a lot of errors in logs.

### PR DESCRIPTION
**Pull request by vasilevalex**
Fixes #1484 
I made it exactly like in dispatcher module.
Please review.

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
@vasilevalex please see my comment on #1484 about the "socket" field in the "dr_gateways" table.

**Comment by bogdan-iancu** [comment]
OK, I see your point. In this case, the per-gateway socket must have override the global socket, as it is more specific. You need to change the condition when pickup the socket for the pinging - if no per-gw socket -> use the global socket ; right now is the other way around. Please be sure this behavior is described in the documentation for the newly added probing_sock parameter.
Also, I suggest the `probing_socket` name versus the shorter `probing_sock` - clarity must come first :).
And please remove the README file from the commit and keep only the `.xml` file - the README files are autogenerated.

**Comment by vasilevalex** [comment]
@bogdan-iancu I made changes. Sorry, didn't know about README files. Is it clear about socket priorities in docs?

**Comment by bogdan-iancu** [comment]
That is perfect, thank you @vasilevalex

**Comment by bogdan-iancu** [comment]
@vasilevalex , thank to @nikbyte , I realized your PR was against 2.4, not master - all the new features must be against master. I "migrated" the patch from 2.4 to master.

**Comment by vasilevalex** [comment]
@bogdan-iancu Ok, next time I'll use master. I didn't know and took the branch which I use...

**Comment by spacetourist** [comment]
Hi @bogdan-iancu - just wondering if/when this might make its way into a point release for 2.4? I have the same situation as #1484 and only my primary node can be enabled to send probes until this feature is available. Many thanks!

**Comment by bogdan-iancu** [comment]
@spacetourist  - as this is a new feature, it will not be backported to 2.4 . 2.4 is a stable release and only fixes are accepted for it.

**Comment by spacetourist** [comment]
@bogdan-iancu OK, thanks for the update. I'll factor that in. Looking forward to 3.0 :+1:

**Pull request merged**
