### PR TITLE
Cachedb and db correct parsing URL with ipv6 address

### LINKED ISSUE #1557: db and cachedb can't parse ipv6 address from config
Both db and cachedb parse URL from config almost the same
`scheme://[username[:password]@]hostname[:port]/database[?parameters]` (for db)
`scheme[:group]://[username[:password]@]hostname[:port]/database` (for cachedb)

But in both cases if I write like this:
`modparam("db_virtual", "db_urls", "mysql://opensips:password@[2001:5c8:4e00:11:a213:ba2d:579a:3e3d]/opensips_test")`
or
`modparam("cachedb_redis", "cachedb_url", "redis:group1://[2001:5c8:4e00:11:a213:ba2d:579a:3e3d]:6379/")`

I get errors:

Dec 10 06:56:10 test82 /usr/sbin/opensips[1437]: ERROR:db_mysql:db_mysql_connect: driver error(2005): Unknown MySQL server host '[2001' (0)
Dec 10 06:56:10 test82 /usr/sbin/opensips[1437]: ERROR:db_mysql:db_mysql_new_connection: initial connect failed

Dec 10 07:01:05 test82 /usr/sbin/opensips[2136]: ERROR:cachedb_redis:redis_get_ctx: failed to open redis connection [2001:0 - Name or service not known
Dec 10 07:01:05 test82 /usr/sbin/opensips[2136]: ERROR:cachedb_redis:redis_new_connection: failed to connect to DB

But with ipv4 address everything works fine.

### PR DESCRIPTION
**Pull request by vasilevalex**
Fixes #1557 
Please review.

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
@vasilevalex , the patch looks fine, I will accept the PR on master, but I will wait couple of weeks before backporting to 2.4 / 2.2, just to be sure there are no side effects.

**Comment by bogdan-iancu** [comment]
Many thanks, Bogdan

**Comment by vasilevalex** [comment]
Hi @bogdan-iancu , yes of course. As I use 2.4, I have patches for it. Cachedb is the same for master and 2.4, db was changed in master, so https://github.com/vasilevalex/opensips/tree/cachedb_url_ipv6_24.

**Comment by bogdan-iancu** [comment]
@vasilevalex , the backport to 2.4 and 2.2 was done, including the later fix did by @razvancrainea

**Pull request merged**
