### PR TITLE
Build debian packages against libssl 1.0 to fix segfault and locking issues

### PR DESCRIPTION
**Pull request by hafkensite**
Fix for issue #1590, in which OpenSIPS 2.4 sefaults on concurrent TLS connections. 
This PR updates the Debian control to ensure libssl 1.0 is used. 

The issue seems to be fixed in master/3.0 by the changes in the tls domain matching.

### CODE REVIEW

**Comment by wdoekes** [comment]
Perhaps amend the commit msg with the "why"

**Comment by volga629** [comment]
We see libssl locking issue on fedora server too force downgrade to 1.0 will might introduce unsupported problems or vulnerabilities. I think gnutls is might be optimal. But from another hand right opensips tls implementation are not suitable for production on latest Linux distros with libssl 1.1

**Comment by bogdan-iancu** [comment]
This is a bit of a radical workaround - it may create a bit of a mess in terms of OS installation. And it works only when deploying from packages. If you simply compile and install, you are still in big problems.
We already have on the TODO list to find out a fix at the code level, to try to eliminate the deadlock in the ssl lib by the way we are using it. There are no simple solutions here, still this is the plan

**Comment by hafkensite** [comment]
That would mean that the TLS packages on the official apt repository of OpenSIPS are useless (or worse, they work initially but let you down when concurrency triggers the bug).

I understand that the proper way forward is to have a better handling of the deadlocks in the ssl lib. Are there plans to also include this in the 2.4 branch, or is that just for 3.0? 
Otherwise I would prefer the official 2.4 packages that are provided to be compiled against openssl 1.0.

**Comment by bogdan-iancu** [comment]
This is obsoleted / fixed by 3d9132e722c18c048a66320265977654bccfa341 and 1b624d2d46bf07e9b0b1f198a93267392371a2e8

**Pull request closed without merging**
