### PR TITLE
Update homepage to use https

### PR DESCRIPTION
**Pull request by l2dy**
This is mostly just search and replace, please review carefully.

Website URL in the repository page should be updated too.

### CODE REVIEW

**Comment by l2dy** [comment]
`http://opensips.org/` will be done in another PR to make review easier, if this one is acceptable.

**Comment by liviuchircu** [comment]
I have yet to review all URLs, but since we're doing this, could you also replace any links containing `"opensips.org/html/docs/modules"` with the more simple `"opensips.org/docs/modules"`?  Once that's ready, I'll go through all URLs one last time and merge it.  Thanks!

**Comment by l2dy** [comment]
So you would prefer all URL changes in one commit?

**Comment by liviuchircu** [comment]
Yes, I think it would make most sense.  "Fix homepage URLs" commit title, for example.

**Comment by liviuchircu** [comment]
If you'd like to do more commits/PRs, I don't mind it at all, by the way!  Total review time is similar anyway :)

**Comment by l2dy** [comment]
> I have yet to review all URLs, but since we're doing this, could you also replace any links containing `"opensips.org/html/docs/modules"` with the more simple `"opensips.org/docs/modules"`? Once that's ready, I'll go through all URLs one last time and merge it. Thanks!

Fixed and force-pushed, please review!

**Comment by liviuchircu** [comment]
Nice work, thank you!

**Comment by l2dy** [comment]
> Website URL in the repository page should be updated too.

BTW, website URL is the one at https://github.com/OpenSIPS/opensips. URL of the https://github.com/OpenSIPS organization should be updated too.

**Comment by liviuchircu** [comment]
> website URL is the one at https://github.com/OpenSIPS/opensips.

Fixed

> URL of the https://github.com/OpenSIPS organization should be updated too.

Will have it fixed.  The website redirects HTTP -> HTTPS anyway, so it's not that big of a deal ;)

**Comment by l2dy** [comment]
> Will have it fixed. The website redirects HTTP -> HTTPS anyway, so it's not that big of a deal ;)

Only if there is no [sslstrip](https://moxie.org/software/sslstrip/) in the middle. ;)

**Comment by l2dy** [comment]
Not in a hurry of course, redirection works well in safe networks.

**Pull request merged**
