### PR TITLE
tm: clone message in async mode only in request route

### PR DESCRIPTION
**Pull request by lemenkov**
Fixes OpenSIPS/opensips#1948.

See also commit OpenSIPS/opensips@43ed8ed1c91a74346b18b68ed6c85ea5cb9fa8c9.

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>

### CODE REVIEW

**Comment by lemenkov** [comment]
Still waiting for comments.

**Comment by bogdan-iancu** [comment]
@lemenkov , do you call an async op from something else than a request route? I'm asking as this is by design not supported.

**Comment by bogdan-iancu** [comment]
@lemenkov , any update here ?

**Comment by bogdan-iancu** [comment]
Still waiting for comments :)

**Comment by lemenkov** [comment]
A better fix provided in #3447. Thanks!

**Pull request closed without merging**
