### PR TITLE
ci: add cifuzz integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Add cifuzz integration so oss-fuzz fuzzers are run 600 secs each PR

Signed-off-by: David Korczynski <david@adalogics.com>

**Summary**

This adds CI integration with CIFuzz. CIFuzz will run the opensips OSS-Fuzz fuzzers (see this issue here https://github.com/OpenSIPS/opensips/issues/2625) for a short period of time for each PR. The benefit is that regressions and bugs has a chance of being captured early in the development process.

**Details**

CIFuzz is the Github action for OSS-Fuzz.

**Solution**

**Compatibility**

No compatibility issues.

**Closing issues**

### CODE REVIEW

**Comment by liviuchircu** [comment]
Hey, @DavidKorczynski and thanks for this!  Could you make it run on every `push` instead of every `pull_request`?  (_I hope i got the verb right..._)

The reason for this is that 90%+ of OpenSIPS contributions to `master` branch are made via `git push`, rather than by clicking "Merge Pull Request".

**Comment by DavidKorczynski** [comment]
I added `push` now - I enabled both as I figured having on pull as well doesn't hurt?

**Review by liviuchircu — APPROVED** [review]
LGTM!

**Comment by DavidKorczynski** [comment]
Argh, we are actually running into an issue here because of CIFuzz. The issue is that the fuzzers are placed in OSS-Fuzz repo rather than opensips, and CIFuzz does some stuff where it deletes the opensips repository and then reclones it, which causes the fuzzers to be removed. The issue is known (https://github.com/google/oss-fuzz/issues/6755) and I have run into it with another project. I should be able to do a quick fix on the OSS-Fuzz repository. Will ping you shortly when the fix has been deployed @liviuchircu

**Comment by DavidKorczynski** [comment]
It works now in my fork @liviuchircu (https://github.com/DavidKorczynski/opensips/actions) so I think it should work if you retrigger the CI

**Comment by liviuchircu** [comment]
That's great!  Thank you, @DavidKorczynski!

**Pull request merged**
