### PR TITLE
B2B: generation of 491 request pending on BYE is not the best idea

### PR DESCRIPTION
**Pull request by nikbyte**

### CODE REVIEW

**Comment by rvlad-patrascu** [comment]
Hi @nikbyte 

If we're not generating a 491 reply I think that the BYE should end the dialog and not be simply discarded(as it would happen if merging this).

**Comment by nikbyte** [comment]
Usually this occurred when we already answered BYE (and finished dialog) and these are retransmits. When dialog is already not found.

**Comment by rvlad-patrascu** [comment]
So I guess that this change was only to fix the crashes reported in https://github.com/OpenSIPS/opensips/issues/2425, correct? In that case, I think that the better approach is to find a proper fix for that. Because as you were saying, this seems more of an work-around.

**Comment by nikbyte** [comment]
Yes. It's for case #2425. If you see the root reason, of course proper fix appreciated.

**Comment by rvlad-patrascu** [comment]
Closing this at the moment since it does not appear to be a proper fix for https://github.com/OpenSIPS/opensips/issues/2425 or the correct approach for handling a BYE when another request is pending.

**Pull request closed without merging**
