### PR TITLE
New SHA transformations: s.sha[1|224|256|384|512] and s.sha[1|224|256|384|512]_hmac

### PR DESCRIPTION
**Pull request by nikbyte**
New SHA transformations: s.sha1, s.sha224, s.sha256, s.sha384, s.sha512.

Thanks @razvancrainea for his advices how to make it properly.

### CODE REVIEW

**Comment by nikbyte** [comment]
I made this again, better way, no repeating code and added 5 more transformations.
Now it's sha and sha_hmac for SHA 1,224,256,384,512.

Usage:
```
    $var(value) = "test";
    $var(key) = "key";
    xlog("L_INFO", "sha1 [$(var(value){s.sha1})]\n");
    xlog("L_INFO", "sha224 [$(var(value){s.sha224})]\n");
    xlog("L_INFO", "sha256 [$(var(value){s.sha256})]\n");
    xlog("L_INFO", "sha384 [$(var(value){s.sha384})]\n");
    xlog("L_INFO", "sha512 [$(var(value){s.sha512})]\n");
    xlog("L_INFO", "sha1_hmac [$(var(value){s.sha1_hmac,$var(key)})]\n");
    xlog("L_INFO", "sha224_hmac [$(var(value){s.sha224_hmac,$var(key)})]\n");
    xlog("L_INFO", "sha256_hmac [$(var(value){s.sha256_hmac,$var(key)})]\n");
    xlog("L_INFO", "sha384_hmac [$(var(value){s.sha384_hmac,$var(key)})]\n");
    xlog("L_INFO", "sha512_hmac [$(var(value){s.sha512_hmac,$var(key)})]\n");
```

And there is no more LGTM analysis warning.

**Comment by nikbyte** [comment]
up

**Review by liviuchircu — APPROVED** [review]
LGTM, the new logic is fully decoupled from existing code, which makes the entire PR safer to accept (any remaining issues will most likely be found in the new SHA transformation functions themselves, rather than as regressions on the existing logic).

**Comment by bogdan-iancu** [comment]
@nikbyte , I assume this new code does not come with any additional external lib deps for the opensips core, right ?

**Comment by nikbyte** [comment]
@bogdan-iancu it uses polarssl parts only, no any external linking.

**Comment by bogdan-iancu** [comment]
@nikbyte , one last thing (truly last) , could you provide me the text (formatting is not needed) for documenting these new transformations, following the model here https://www.opensips.org/Documentation/Script-Tran-3-3 ?

**Comment by nikbyte** [comment]
1.31 {s.sha1} 🔗

Returns the SHA1 hash of the given input.
xlog("SHA1 over From username: $(fU{s.sha1})\n");

1.32 {s.sha224} 🔗

Returns the SHA224 hash of the given input.
xlog("SHA224 over From username: $(fU{s.sha224})\n");

1.33 {s.sha256} 🔗

Returns the SHA256 hash of the given input.
xlog("SHA256 over From username: $(fU{s.sha256})\n");

1.34 {s.sha384} 🔗

Returns the SHA384 hash of the given input.
xlog("SHA384 over From username: $(fU{s.sha384})\n");

1.35 {s.sha512} 🔗

Returns the SHA512 hash of the given input.
xlog("SHA512 over From username: $(fU{s.sha512})\n");

1.36 {s.sha1_hmac} 🔗

Returns the SHA1 HMAC hash of the given input.
xlog("SHA1 HMAC over From username: $(fU{s.sha1_hmac})\n");

1.37 {s.sha224_hmac} 🔗

Returns the SHA224 HMAC hash of the given input.
xlog("SHA224 HMAC over From username: $(fU{s.sha224_hmac})\n");

1.38 {s.sha256_hmac} 🔗

Returns the SHA256 HMAC hash of the given input.
xlog("SHA256 HMAC over From username: $(fU{s.sha256_hmac})\n");

1.39 {s.sha384_hmac} 🔗

Returns the SHA384 HMAC hash of the given input.
xlog("SHA384 HMAC over From username: $(fU{s.sha384_hmac})\n");

1.40 {s.sha512_hmac} 🔗

Returns the SHA512 HMAC hash of the given input.
xlog("SHA512 HMAC over From username: $(fU{s.sha512_hmac})\n");

**Comment by nikbyte** [comment]
1.31 {s.sha1} 🔗

Returns the SHA1 hash of the given input.
xlog("SHA1 over From username: $(fU{s.sha1})\n");

1.32 {s.sha224} 🔗

Returns the SHA224 hash of the given input.
xlog("SHA224 over From username: $(fU{s.sha224})\n");

1.33 {s.sha256} 🔗

Returns the SHA256 hash of the given input.
xlog("SHA256 over From username: $(fU{s.sha256})\n");

1.34 {s.sha384} 🔗

Returns the SHA384 hash of the given input.
xlog("SHA384 over From username: $(fU{s.sha384})\n");

1.35 {s.sha512} 🔗

Returns the SHA512 hash of the given input.
xlog("SHA512 over From username: $(fU{s.sha512})\n");

1.36 {s.sha1_hmac,key} 🔗

Returns the SHA1 HMAC hash of the given input using key.
xlog("SHA1 HMAC over From username using key 'secret': $(fU{s.sha1_hmac,secret})\n");

1.37 {s.sha224_hmac,key} 🔗

Returns the SHA224 HMAC hash of the given input using key.
xlog("SHA224 HMAC over From username using key 'secret': $(fU{s.sha224_hmac,secret})\n");

1.38 {s.sha256_hmac,key} 🔗

Returns the SHA256 HMAC hash of the given input using key.
xlog("SHA256 HMAC over From username using key 'secret': $(fU{s.sha256_hmac,secret})\n");

1.39 {s.sha384_hmac,key} 🔗

Returns the SHA384 HMAC hash of the given input using key.
xlog("SHA384 HMAC over From username using key 'secret': $(fU{s.sha384_hmac,secret})\n");

1.40 {s.sha512_hmac,key} 🔗

Returns the SHA512 HMAC hash of the given input using key.
xlog("SHA512 HMAC over From username using key 'secret': $(fU{s.sha512_hmac,secret})\n");

**Pull request merged**
