### PR TITLE
Add updating xlog_print_level in set_local_xlog_level

### PR DESCRIPTION
**Pull request by Shkiperon**
Looks like this update of variable was missed when xlog.c was updated.
Linked issue: https://github.com/OpenSIPS/opensips/issues/2329

### CODE REVIEW

**Review by liviuchircu — CHANGES_REQUESTED** [review]
Hey, @Shkiperon!  First of all, let's clear up what problem you are trying to solve.  In `3.1`, a new global was added, [`xlog_level`](https://www.opensips.org/Documentation/Script-CoreParameters-3-2#xlog_level), which decouples engine logging from scripting logging.

The [`xlog_print_level`](https://www.opensips.org/Documentation/Script-CoreParameters-3-2#xlog_print_level) global controls the default logging level of [`xlog()`](https://www.opensips.org/Documentation/Script-CoreFunctions-3-2#toc55) statements which do not include the "log_level" parameter.

I do not see why setting the `$xlog_level` variable for a SIP worker would also have to force a different _default xlog() logging level_ for that worker -- the two settings do not seem to have much in common.

What do you think?

**Comment by liviuchircu** [comment]
Update: just noticed issue #2329, where you describe an actual bug, related to `xlog()` and shipping the log to Homer.  Let me come back to you once I understand it.

**Comment by Shkiperon** [comment]
As I already wrote in my issue - I found a problem that is expressed in the fact that in the HEP-package from OpenSIPS, events with the LOG type go towards the heplify-server with the default event level (ERROR) even if I change it in the script. My knowledge of the C language was only enough to understand that the problem is somewhere in xlog.c. When testing on OpenSIPS 2.4.8, this problem does not occur.

**Comment by liviuchircu** [comment]
Could you clean up your changes, then apply the following small patch after placing yourself in the `opensips/` source code directory and see if it works?  As I see it, the line changed by the patch is all we need to fix here.

```
git apply <(base64 -d <<EOF | gzip -dc
H4sIAM3U0F8AA02NwW6DMBBEz/grVjlBiGko0ChFlVK1OVTKIYo49GZtbENWJQRhK43Un68hiFZ7
mPXMPo+isgTOK7KAD7f6UkUSjuPCqFH6BkmcpEmWaRlFyTpLyjTFDOLl8ilNGed84lgYhn/sZgM8
Xj0uVhDexRnGoiUJ1NTUaLheSAEqJXpCKLTo2w6lFmdtDFYaRl0Ml3NoscNzwMAbvzG2A0Ot6PWl
fwlqyPoz582CnIEb7plvsvIE/tDRdtRYUeurrgP4YeGUzod4CsDzJBoNO/G62x6K597w+oLhIjKu
7n1/z0Sx/SxyOHYav/J/4Nvhw3G/2TRJn14BAAA=
EOF
)
```

**Comment by Shkiperon** [comment]
Yes, I'll try to do it tomorrow. I will give feedback on the results.

**Comment by Shkiperon** [comment]
@liviuchircu your patch has fixed my problem. Thank you

**Comment by liviuchircu** [comment]
Just merged the fix and closed both issues. Thank you for your help!

**Pull request closed without merging**
