### PR TITLE
:bug: fix parameter typo

### PR DESCRIPTION
**Pull request by spacetourist**
Self explanatory!

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
@spacetourist , nice catch, but please remove the README file from the PR - that file is auto-generated.

**Comment by spacetourist** [comment]
Sure, will do that now @bogdan-iancu - is there something i need to run to generate them or shall i leave that up to you?

**Comment by spacetourist** [comment]
hopefully thats better now, let me know if you need anything else. thanks!

**Comment by liviuchircu** [comment]
Hey, guys!  I just tidied up the PR branch a bit, by squashing 3 commits into 2.  Cheers, @spacetourist!

**Pull request merged**
