### PR TITLE
Changed from VAL_STR to VAL_STRING in case DB_STRING

### PR DESCRIPTION
**Pull request by Danfx**
it's a suggestion to standard

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
Hi @Danfx ! the existing code returns STR, but the value can be used as STRING or STR in the same time (on a similar model for DB_TEXT driver). With your change the type and the value are STRING only.
By "standard" you mean the fact that most modules (using a DB backend) expect STRING and not STR ?

**Comment by Danfx** [comment]
No, I'm analyzing only this case ('case DB_STRING:') from switch. If you are using a VAL_TYPE(_v) equal DB_STRING, I guess it would be more elegant to use a structure of the DB_STRING ('VAL_STRING(_v)')
like as in other software points:
[https://github.com/OpenSIPS/opensips/blob/master/modules/db_sqlite/val.c#L95](https://github.com/OpenSIPS/opensips/blob/master/modules/db_sqlite/val.c#L95)
[https://github.com/OpenSIPS/opensips/blob/master/db/db_row.c#L68](https://github.com/OpenSIPS/opensips/blob/master/db/db_row.c#L68)
[https://github.com/OpenSIPS/opensips/blob/master/modules/db_oracle/res.c#L343](https://github.com/OpenSIPS/opensips/blob/master/modules/db_oracle/res.c#L343)

**Comment by ionutrazvanionita** [comment]
merged manually

**Comment by jarrodb** [comment]
I'm pretty sure you just broke clusterer which is one of the reasons it was changed: https://github.com/OpenSIPS/opensips/pull/844

Forgive me if I'm wrong...

**Pull request closed without merging**
