### PR TITLE
b2b_logic: Fix parsing of uri in header

### PR DESCRIPTION
**Pull request by nikbyte**
I found an issue in b2b when process REFER.

I use next rule in xml:
```
<destination>
    <value type="header">Refer-To</value>
</destination>
```

When b2b_logic processes Refer-To header in REFER and the header has content like `"display name" <sip:name@domain.com>`, the b2b_logic module can't parse url there. This patch fixes this issue.

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
Thanks @nikbyte , indeed, this is an issue - so far it was not a big problem, as the devices are usually not pushing a display name into the REFER header, nevertheless, a totally valid options.
I will check the patch and update here.

**Comment by nikbyte** [comment]
However softphones do this. For example, zoiper.

**Comment by bogdan-iancu** [comment]
@nikbyte , could you try my alternative patch, it gets rid of some memory leaks ;). NOTE that the hdr here may be anything , like the "Foo" hdr. And OpenSIPS will have no idea how to free the parsed-body of such unknown hdr - so, adding the "to_body" to the "parsed" holder will result in a leak, as (again) OpenSIPS will not attempt to free it.

**Comment by bogdan-iancu** [comment]
please give a try to my alternative fix and let me know if it does the job ;). Thanks !!

**Comment by nikbyte** [comment]
Bogdan, thank you. Your patch is perfect and works well.

**Comment by bogdan-iancu** [comment]
thank you @nikbyte for the testing , still [this line](https://github.com/OpenSIPS/opensips/pull/2371/files#diff-a109e5901c39ef82abfdc8353930f5a3c7504f3658e8b4af42e7021d6f75ec05R593) did not make it into my patch. 
I see it is very similar to #2374 - what is the plan here ?

**Comment by bogdan-iancu** [comment]
Ok, the pending line from the PR is a NO-GO, thanks @nikbyte for the confirmation.

**Pull request closed without merging**
