### PR TITLE
load balancer: new parameter to lb_start/next

### PR DESCRIPTION
**Pull request by shripchenko**
Added optional parameter [dsts_cnt] to lb_start/next family of functions that holds a string containing an integer PV (pseudo-variable) where the total number of matching destinations (regardless of their capacity) will be stored.

This could be used to distinguish between 'no capacity' and 'no destinations left' situations upon a failure to find out an available destination.

### CODE REVIEW

**Comment by bogdan-iancu** [comment]
Hi @shripchenko  - sorry for the late handling of this PR. Aside making a difference between no capacity' and 'no destinations left', do you see any other usage case of this new "dsts_cnt" param ?

**Comment by shripchenko** [comment]
mmm.
not sure i could provide you more scenarios.
for our usage scenario we had to know, whenever the call failed for 'no capacity' or for 'no destinations left' scanarios, to adjust fail-over scenario.

**Comment by bogdan-iancu** [comment]
@shripchenko , in this case, what about propagating the info "no channels available" or "bad resources" via return code rather than a variable ?

**Comment by bogdan-iancu** [comment]
@shripchenko , any opinion on this ? if not, I will rework the patch to get the functionality based on the return code.

**Comment by shripchenko** [comment]
sure! no prob.
thanks!

**Pull request closed without merging**
