### PR TITLE
Fix cachedb_redis crash

### LINKED ISSUE #2803: [CRASH] cachedb_redis crash due to network event
**OpenSIPS version you are running**
```
version: opensips 3.1.8 (x86_64/linux)
flags: STATS: On, DISABLE_NAGLE, USE_MCAST, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, HP_MALLOC, DBG_MALLOC, CC_O0, FAST_LOCK-ADAPTIVE_WAIT
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535
poll method support: poll, epoll, sigio_rt, select.
main.c compiled on 18:55:25 Apr  5 2022 with gcc 8
```

**Crash Core Dump**
```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f9e49067535 in __GI_abort () at abort.c:79
#2  0x00007f9e490be518 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f9e491c828d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f9e490c4c3a in malloc_printerr (str=str@entry=0x7f9e491c643b "free(): invalid pointer") at malloc.c:5359
#4  0x00007f9e490c646c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4180
#5  0x00007f9e3cec3dc3 in sdsMakeRoomFor () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.14
#6  0x00007f9e3cec47dc in sdscatlen () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.14
#7  0x00007f9e3cec35a0 in __redisAppendCommand () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.14
#8  0x00007f9e3cec362c in redisvAppendCommand () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.14
#9  0x00007f9e3cec3810 in redisvCommand () from /usr/lib/x86_64-linux-gnu/libhiredis.so.0.14
#10 0x00007f9e3ced8614 in redis_raw_query_send (connection=0x7f9e458e33a8, reply=0x7ffd4f0b6b08, rpl=0x7ffd4f0b6c58, expected_kv_no=1, reply_no=0x7ffd4f0b6c54, attr=0x7ffd4f0b6d10)
    at cachedb_redis_dbase.c:684
#11 0x00007f9e3ced89f2 in redis_raw_query (connection=0x7f9e458e33a8, attr=0x7ffd4f0b6d10, rpl=0x7ffd4f0b6c58, expected_kv_no=1, reply_no=0x7ffd4f0b6c54) at cachedb_redis_dbase.c:721
#12 0x000056390222aae3 in cachedb_raw_query (cachedb_name=0x7ffd4f0b6cf8, attr=0x7ffd4f0b6d10, reply=0x7ffd4f0b6c58, expected_kv_no=1, rpl_no=0x7ffd4f0b6c54) at cachedb/cachedb.c:761
#13 0x00005639020f7a35 in w_cache_raw_query (msg=0x7f9e458e3820, id=0x7ffd4f0b6cf8, raw_query_s=0x7ffd4f0b6d10, avp_list=0x7f9e450910e8) at core_cmds.c:1153
#14 0x00005639020ed100 in do_action (a=0x7f9e4506b078, msg=0x7f9e458e3820) at action.c:974
#15 0x00005639020e9986 in run_action_list (a=0x7f9e4506b078, msg=0x7f9e458e3820) at action.c:158
#16 0x00005639021296c1 in eval_elem (e=0x7f9e4506b1d0, msg=0x7f9e458e3820, val=0x0) at route.c:602
#17 0x000056390212a7f6 in eval_expr (e=0x7f9e4506b1d0, msg=0x7f9e458e3820, val=0x0) at route.c:926
#18 0x000056390212a8f0 in eval_expr (e=0x7f9e4506b268, msg=0x7f9e458e3820, val=0x0) at route.c:942
#19 0x00005639020ec174 in do_action (a=0x7f9e4506b6f8, msg=0x7f9e458e3820) at action.c:739
#20 0x00005639020e9986 in run_action_list (a=0x7f9e45067be0, msg=0x7f9e458e3820) at action.c:158
#21 0x00005639020e9840 in run_actions (a=0x7f9e45067be0, msg=0x7f9e458e3820) at action.c:123
#22 0x00005639020e9ccf in run_top_route (a=0x7f9e45067be0, msg=0x7f9e458e3820) at action.c:241
#23 0x00005639020fd21e in receive_msg (
    buf=0x56390242fe20 <buf> "INVITE sip:1000@192.168.1.24:5060 SIP/2.0\r\nVia: SIP/2.0/UDP 192.168.1.21:5060;branch=z9hG4bK-1264-9-0\r\nFrom: <sip:2000@192.168.1.21:5060>;tag=vts12649\r\nTo: <sip:1000@192.168.1.24:5060>\r\nCall-ID: 9-126"..., len=651, rcv_info=0x7ffd4f0b7330, existing_context=0x0, msg_flags=0) at receive.c:213
#24 0x0000563902250057 in udp_read_req (si=0x7f9e45064eb8, bytes_read=0x7ffd4f0b73f8) at net/proto_udp/proto_udp.c:186
#25 0x0000563902231f7d in handle_io (fm=0x7f9e45091708, idx=0, event_type=1) at net/net_udp.c:272
#26 0x00005639022307d8 in io_wait_loop_epoll (h=0x56390241a020 <_worker_io>, t=1, repeat=0) at net/../io_wait_loop.h:305
#27 0x00005639022331f3 in udp_start_processes (chd_rank=0x563902419edc <chd_rank>, startup_done=0x0) at net/net_udp.c:497
#28 0x000056390216e6b3 in main_loop () at main.c:802
#29 0x0000563902171ce0 in main (argc=15, argv=0x7ffd4f0b76d8) at main.c:1491
```

**Describe the traffic that generated the bug**
Crash occurs when network connection to redis becomes broken, or when there is significant packet loss between OpenSIPS and redis.

**To Reproduce**
1. Start opensips with this [minimal config](https://github.com/OpenSIPS/opensips/files/8421924/minimal.txt)
2. Simulate packet loss on redis server via iptables. Example:
- `iptables -A INPUT -s 192.168.1.24 -m statistic --mode random --probability 0.50 -j DROP`
3. Send a few calls and crash will occur.

**Relevant System Logs**
```
Apr  5 21:16:08 [45] ERROR:cachedb_redis:redis_get_ctx: failed to open redis connection 192.168.1.16:6379 - Connection timed out
Apr  5 21:16:08 [45] ERROR:cachedb_redis:redis_new_connection: failed to connect to DB
Apr  5 21:16:08 [45] WARNING:core:handle_timer_job: utimer job <tm-utimer> has a 280000 us delay in execution
Apr  5 21:16:08 [46] ERROR:cachedb_redis:redis_get_ctx: failed to open redis connection 192.168.1.16:6379 - Connection timed out
Apr  5 21:16:08 [46] ERROR:cachedb_redis:redis_connect: failed to init connection 
Apr  5 21:16:08 [46] ERROR:cachedb_redis:redis_new_connection: failed to connect to DB
Apr  5 21:16:16 [45] ERROR:cachedb_redis:redis_get_ctx: failed to open redis connection 192.168.1.16:6379 - Connection timed out
Apr  5 21:16:16 [45] ERROR:cachedb_redis:redis_raw_query_send: giving up on query
Apr  5 21:16:16 [45] ERROR:cachedb_redis:redis_raw_query: Failed to send query to server 
Apr  5 21:16:16 [45] failed to query redis
Apr  5 21:16:17 [45] ERROR:cachedb_redis:redis_connect_node: failed to select database 1 - FAILURE
Apr  5 21:16:17 [45] ERROR:cachedb_redis:redis_raw_query: Failed to send query to server 
Apr  5 21:16:17 [45] failed to query redis
free(): invalid pointer
```

**OS/environment information**
 - Operating System: `Debian 10`
 - OpenSIPS installation: `git nightly 3.1.8`
 - other relevant information: crash occurs on all version of hiredis

### PR DESCRIPTION
**Pull request by john08burke**
fixes #2803

### CODE REVIEW

**Comment by john08burke** [comment]
Unfortunately it looks like master has diverged a bit from 3.1 in the `cachedb_redis` module.  The PR I submitted fixes master, but this is the [patch](https://github.com/OpenSIPS/opensips/files/8422030/fix-diff.txt) needed for 3.1.  I actually only tested it on 3.1 as I haven't upgraded yet, but the logic looked the same in master.

Assuming it looks good, do you want a separate PR for the 3.1 branch?

**Comment by bogdan-iancu** [comment]
@john08burke , yes, please create a separate PR for 3.2 (or 3.1) and I will do the cherry-pick between them. Thanks!

**Comment by john08burke** [comment]
Hey @bogdan-iancu, this one can be cherry-picked down to 3.2.  I will put in a PR for 3.1 shortly.

**Comment by bogdan-iancu** [comment]
Thank you @john08burke , much appreciated here !

**Pull request merged**
